---
title: "Tidyr"
author: "Disem_Sula"
format: html
editor: visual
---

## Tidyr and ggplot2

```{r}
#| message: false
#| echo: false
here::i_am("git_101_new.Rproj")
library(here)
library(ggplot2)
library(tidyr)
library(dplyr)
```

### Multiple lines on a single graph

```{r dax stock}
eustock <- as.data.frame(EuStockMarkets)
eustock <- eustock |> mutate(time=1:n())
ggplot(eustock, aes(x=time, y=DAX)) +
  geom_line()
```

### Strong solution

```{r dax + cac stock}
ggplot(eustock, aes(x=time, y=DAX)) +
  geom_line() +
  geom_line(mapping = aes(y=CAC), color="red")
```

Problems:
y axes name is wrong
colors must be specified normally
we miss association between colors and names

#### Tidyr based solution

```{r long eu stock}
long_eustock <- 
  eustock |> 
  pivot_longer(-time, names_to = "stock index", values_to = "Value")
```

```{r long eu stock lines}
ggplot(long_eustock, aes(x=time, y=Value, group: `stock index`), color = `stock index`) +
  geom_line()
```

```{r long eu facet}
ggplot(long_eustock, aes(x=time, y=Value, group: `stock index`), color = `stock index`) +
  geom_line() +
  facet_wrap(~`stock index`, ncol=1, scales = "free_y")
```

